name: 'Run main workflow'

on:
  pull_request:
  push:
    branches:
      - "master"
    tags:
      - "*"

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  check-formatting:
    runs-on: "ubuntu-latest"
    timeout-minutes: 30
    if: github.ref_type != 'tags'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Configure Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Run formatting check
        run: cargo fmt --all -- --check
  lint:
    runs-on: "ubuntu-latest"
    timeout-minutes: 30
    if: github.ref_type != 'tags'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Configure Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Run lint
        run: cargo clippy --all-features --all-targets
  test-linux:
    runs-on: "ubuntu-latest"
    timeout-minutes: 30
    if: github.ref_type != 'tags'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Configure Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test
  test-windows:
    runs-on: "windows-latest"
    timeout-minutes: 30
    if: github.ref_type != 'tags'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Configure Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test
  test-macos:
    runs-on: "macos-latest"
    timeout-minutes: 30
    if: github.ref_type != 'tags'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Configure Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test
  build-linux:
    runs-on: "ubuntu-latest"
    timeout-minutes: 30
    if: github.event_name != 'pull_request' && !failure()
    needs:
      - test-linux
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Configure Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Run build
        run: cargo build --release
      - name: Rename binary
        run: mv target/release/has-my-alias-been-pwned target/release/has-my-alias-been-pwned-linux
      - name: Temporarily save linux binary
        uses: actions/upload-artifact@v6
        with:
          name: has-my-alias-been-pwned-linux
          path: target/release/has-my-alias-been-pwned-linux
          retention-days: 1
  build-windows:
    runs-on: "windows-latest"
    timeout-minutes: 30
    if: github.event_name != 'pull_request' && !failure()
    needs:
      - test-windows
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Configure Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Run build
        run: cargo build --release
      - name: Rename binary
        run: mv target\release\has-my-alias-been-pwned.exe target\release\has-my-alias-been-pwned-windows.exe
      - name: Temporarily save windows binary
        uses: actions/upload-artifact@v6
        with:
          name: has-my-alias-been-pwned-windows
          path: target\release\has-my-alias-been-pwned-windows.exe
          retention-days: 1
  build-macos:
    runs-on: "macos-latest"
    timeout-minutes: 30
    if: github.event_name != 'pull_request' && !failure()
    needs:
      - test-macos
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Configure Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Run build
        run: cargo build --release
      - name: Rename binary
        run: mv target/release/has-my-alias-been-pwned target/release/has-my-alias-been-pwned-macos
      - name: Temporarily save mac os binary
        uses: actions/upload-artifact@v6
        with:
          name: has-my-alias-been-pwned-macos
          path: target/release/has-my-alias-been-pwned-macos
          retention-days: 1
  release:
    runs-on: "ubuntu-latest"
    timeout-minutes: 30
    if: github.ref_type == 'tag'
    needs:
      - build-linux
      - build-windows
      - build-macos
    steps:
      - name: Retrieve saved linux binary
        uses: actions/download-artifact@v7
        with:
          name: has-my-alias-been-pwned-linux
      - name: Retrieve saved windows binary
        uses: actions/download-artifact@v7
        with:
          name: has-my-alias-been-pwned-windows
      - name: Retrieve saved mac os binary
        uses: actions/download-artifact@v7
        with:
          name: has-my-alias-been-pwned-macos
      - name: Create Release
        uses: ncipollo/release-action@v1.20.0
        with:
          artifacts: has-my-alias-been-pwned-linux,has-my-alias-been-pwned-macos,has-my-alias-been-pwned-windows.exe
          generateReleaseNotes: true
          makeLatest: true

